linters:
  enable-all: true
  disable:
    - golint
    - gomnd
    - interfacer
    - scopelint
    - maligned
    - wsl
    - wrapcheck
    - godox
    - forbidigo
    - nlreturn
    - varnamelen
    - tagliatelle 
    - paralleltest 
    - exhaustivestruct 
    - misspell  
    - lll   
    - godot 
    - gofumpt 
    - funlen 